%------------------------------------------------------------------------
%  Ten_qbit_sample_generation_v0 : program to check the data generation 
%                                    explaind in  the paper J.R. Click 
%                                    "Covariant quantum kernels 
%                                     for data with group structure" 2022
%---------------------------------------------------------------------------

function Ten_qbit_sample_generation_v0
%Symbolic calculations
symbolic = 0;  %Use 1 to get the body of the U function
test_number = 1; % Loops to test functions
samples = 20; % Number of samples to generate
eps = 0.01; %Variance of the random error applyed
seed = 1111;

rng(seed);

% Identity 
I = [ 1 0 
      0 1 ];
% Pauli Matrices
X = [ 0 1
      1 0 ];
Y = [ 0  -1i
      1i   0];
Z = [  1  0 
       0 -1 ];


%-------------------------------------------------------------------------
% Symbolic generation of
% kron( D(theta_1, theta_2,0 ), D(theta_3, theta_4,0))

    if symbolic == 1
    syms theta_1
    Rot1 = [ cos(theta_1/2)    -1i*sin(theta_1/2);
            -1i*sin(theta_1/2)    cos(theta_1/2)  ];

    syms theta_2
    Rot2 = [ exp(-1i*theta_2/2)    0
            0              exp(1i*theta_2/2) ]; 
    syms theta_3
    Rot3 = [ cos(theta_3/2)    -1i*sin(theta_3/2);
            -1i*sin(theta_3/2)    cos(theta_3/2)  ];

    syms theta_4
    Rot4 = [ exp(-1i*theta_4/2)    0
            0              exp(1i*theta_4/2) ];

    Result = kron(Rot1*Rot2, Rot3*Rot4);

    fprintf ('Tensor product decompositon:\n');

    fprintf("M(1,1) = %s; \nM(1,2)= %s;\nM(1,3) = %s;\nM(1,4) = %s;\n",....
             Result(1,1), Result(1,2), Result(1,3), Result(1,4)); 
    fprintf("M(2,1) = %s; \nM(2,2)= %s;\nM(2,3) = %s;\nM(2,4) = %s;\n",....
             Result(2,1), Result(2,2), Result(2,3), Result(2,4));
    fprintf("M(3,1) = %s; \nM(3,2)= %s;\nM(3,3) = %s;\nM(3,4) = %s;\n",....
             Result(3,1), Result(3,2), Result(3,3), Result(3,4)); 
    fprintf("M(4,1) = %s; \nM(4,2)= %s;\nM(4,3) = %s;\nM(4,4) = %s;\n",....
             Result(4,1), Result(4,2), Result(4,3), Result(4,4));    
                 
    end
%-------------------------------------------------------------------------

%-------------------------------------------------------------------- 
%
%  Use of Ten qbits for the architecture:
%  0 --- 1 --- 2 --- 3 --- 4 --- 5 --- 6 --- 7 --- 8 --- 9
%
%  Therefore, we have nine cases:
%  X0Z1
%  X1Z2
%  X2Z3
%  X3Z4
%  X4Z5
%  X5Z6
%  X6Z7
%  X7Z8
%  X8Z9
%--------------------------------------------------------------------

coset = [ 'C-' 
          'C+' ];

for k = 1:test_number
 for j = 1:2
    
    % Indicate the coset
    fprintf ('Coset %s\n', coset(j,:));
    
    % Generate random angles  
    theta_1 = random('uniform', -pi/2, pi/2);
    theta_2 = random('uniform', -pi/2, pi/2);
    theta_3 = random('uniform', -pi/2, pi/2);
    theta_4 = random('uniform', -pi/2, pi/2);
    theta_5 = random('uniform', -pi/2, pi/2);
    theta_6 = random('uniform', -pi/2, pi/2);
    theta_7 = random('uniform', -pi/2, pi/2);
    theta_8 = random('uniform', -pi/2, pi/2);
    theta_9 = random('uniform', -pi/2, pi/2);
    theta_10 = random('uniform', -pi/2, pi/2);
    theta_11 = random('uniform', -pi/2, pi/2);
    theta_12 = random('uniform', -pi/2, pi/2);
    theta_13 = random('uniform', -pi/2, pi/2);
    theta_14 = random('uniform', -pi/2, pi/2);
    theta_15 = random('uniform', -pi/2, pi/2);
    theta_16 = random('uniform', -pi/2, pi/2);
    theta_17 = random('uniform', -pi/2, pi/2);
    theta_18 = random('uniform', -pi/2, pi/2);
    theta_19 = random('uniform', -pi/2, pi/2);
    theta_20 = random('uniform', -pi/2, pi/2);
    
    % Identity 
    Sample = [ theta_1, theta_2, ...
               theta_3, theta_4, ...
               theta_5, theta_6, ...
               theta_7, theta_8, ...
               theta_9, theta_10,...
               theta_11,theta_12,...
               theta_13,theta_14,...
               theta_15,theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];

    fprintf ('Sample R*I    =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f\n',...
              Sample); 
    %----------------------------------------------------------------
    % First case: X0Z1
    % ---  X --- D(0, theta_1, theta_2, 0) --- 
    % ---  Z --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- I ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X0Z1 = kron(X, ...
            kron(Z, ...
                kron(I, ...
                    kron(I, ...
                        kron(I, ...
                            kron (I, ...
                               kron(I, ...
                                 kron(I, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X0Z1;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
           D([0, theta_3, theta_4, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, estimated_angles(1),estimated_angles(2), 0) --- 
    % --- D(0, estimated_angles(3),estimated_angles(4), 0) --- 
    % ----D(0, theta_5, theta_6, 0) --------------------------
    % ----D(0, theta_7, theta_8, 0) --------------------------
    % ----D(0, theta_9, theta_10, 0) -------------------------
    % ----D(0, theta_11, theta_12, 0) ------------------------
    % ----D(0, theta_13, theta_14, 0) ------------------------
    % ----D(0, theta_15, theta_16, 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,estimated_angles(1),estimated_angles(2), 0], I,X,Z,X), ...
          kron( D([0,estimated_angles(3),estimated_angles(4), 0], I,X,Z,X), ...
           kron( D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron( D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron( D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, theta_11, theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                        kron( D([0, theta_15, theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_0 = [ estimated_angles(1),estimated_angles(2), ...
               estimated_angles(3),estimated_angles(4), ...
               theta_5, theta_6, ...
               theta_7, theta_8, ...
               theta_9, theta_10,...
               theta_11,theta_12,...
               theta_13, theta_14,...
               theta_15, theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X0Z1 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_0);
    if j == 1
        writematrix ([Sample_0,j],'Data_10qubit.csv','WriteMode','overwrite');
    else 
        writematrix ([Sample_0,j],'Data_10qubit.csv','WriteMode','append');
    end 
    %----
    %  End of first case 
    %
    %------------------------------------------------------------------
    % Second case: X1Z2 
    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  X --- D(0, theta_3, theta_4, 0) --- 
    % ---- Z ----D(0, theta_5, theta_6, 0) ---
    % ---- I ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X1Z2 = kron(I, ...
            kron(X, ...
                kron(Z, ...
                    kron(I, ...
                        kron(I, ...
                            kron (I, ...
                               kron(I, ...
                                 kron(I, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X1Z2;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           D([0, theta_5, theta_6, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, estimated_angles(1),estimated_angles(2), 0) --- 
    % --- D(0, estimated_angles(3),estimated_angles(4), 0) ---
    % ----D(0, theta_7, theta_8, 0) --------------------------
    % ----D(0, theta_9, theta_10, 0) -------------------------
    % ----D(0, theta_11, theta_12, 0) ------------------------
    % ----D(0, theta_13, theta_14, 0) ------------------------
    % ----D(0, theta_15, theta_16, 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0,estimated_angles(1),estimated_angles(2), 0], I,X,Z,X), ...
           kron( D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X), ...
             kron( D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron( D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, theta_11, theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                        kron( D([0, theta_15, theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_1 = [ theta_1,theta_2, ...
               estimated_angles(1),estimated_angles(2), ...
               estimated_angles(3), estimated_angles(4), ...
               theta_7, theta_8, ...
               theta_9, theta_10,...
               theta_11,theta_12,...
               theta_13, theta_14,...
               theta_15, theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X1Z2 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_1);

    writematrix ([Sample_1,j],'Data_10qubit.csv','WriteMode','append');

    %
    % End of second case
    %-------------------------------------------------------------------
    % Third case: X2Z3
    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- X ----D(0, theta_5, theta_6, 0) ---
    % ---- Z ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X2Z3 = kron(I, ...
            kron(I, ...
                kron(X, ...
                    kron(Z, ...
                        kron(I, ...
                            kron (I, ...
                               kron(I, ...
                                 kron(I, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X2Z3;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
           D([0, theta_7, theta_8, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, estimated_angles(1),estimated_angles(2), 0) ---
    % --- D(0, estimated_angles(3),estimated_angles(4), 0) ---
    % ----D(0, theta_9, theta_10, 0) -------------------------
    % ----D(0, theta_11, theta_12, 0) ------------------------
    % ----D(0, theta_13, theta_14, 0) ------------------------
    % ----D(0, theta_15, theta_16, 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, estimated_angles(1), estimated_angles(2), 0], I, X, Z, X), ...
             kron( D([0, estimated_angles(3),estimated_angles(4), 0], I, X, Z, X), ...
                kron( D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, theta_11, theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                        kron( D([0, theta_15, theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_2 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               estimated_angles(1), estimated_angles(2), ...
               estimated_angles(3), estimated_angles(4), ...
               theta_9, theta_10,...
               theta_11,theta_12,...
               theta_13, theta_14,...
               theta_15, theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X2Z3 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_2);

    writematrix ([Sample_2,j],'Data_10qubit.csv','WriteMode','append');

    % End of third case 
    %---------------------------------------------------------------------
    % Fourth case: X3Z4 
    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- X ----D(0, theta_7, theta_8, 0) ---
    % ---- Z ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X3Z4 = kron(I, ...
            kron(I, ...
                kron(I, ...
                    kron(X, ...
                        kron(Z, ...
                            kron (I, ...
                               kron(I, ...
                                 kron(I, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X3Z4;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
           D([0, theta_9, theta_10, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, theta_5,theta_6, 0) ---
    % --- D(0, estimated_angles(1),estimated_angles(2), 0) ---
    % ----D(0, estimated_angles(3),estimated_angles(4), 0) ---
    % ----D(0, theta_11, theta_12, 0) ------------------------
    % ----D(0, theta_13, theta_14, 0) ------------------------
    % ----D(0, theta_15, theta_16, 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, theta_5,theta_6, 0], I, X, Z, X), ...
             kron( D([0, estimated_angles(1),estimated_angles(2), 0], I, X, Z, X), ...
                kron( D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X), ... 
                   kron( D([0, theta_11, theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                        kron( D([0, theta_15, theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_3 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               theta_5,theta_6, ...
               estimated_angles(1), estimated_angles(2), ...
               estimated_angles(3), estimated_angles(4),...
               theta_11,theta_12,...
               theta_13, theta_14,...
               theta_15, theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X3Z4 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_3);
    writematrix ([Sample_3,j],'Data_7qubit.csv','WriteMode','append');


    % End of fourth case 
    %---------------------------------------------------------------------
    % Fifth case: X4Z5 
    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- X ----D(0, theta_7, theta_8, 0) ---
    % ---- Z ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X4Z5 = kron(I, ...
            kron(I, ...
                kron(I, ...
                    kron(I, ...
                        kron(X, ...
                            kron(Z, ...
                               kron(I, ...
                                 kron(I, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X4Z5;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ...
           D([0, theta_11, theta_12, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, theta_5,theta_6, 0) ---
    % --- D(0, theta_7,theta_8, 0) ---
    % ----D(0, estimated_angles(1),estimated_angles(2), 0) ---
    % ----D(0, estimated_angles(3),estimated_angles(4), 0) ---
    % ----D(0, theta_13, theta_14, 0) ------------------------
    % ----D(0, theta_15, theta_16, 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, theta_5,theta_6, 0], I, X, Z, X), ...
             kron( D([0, theta_7,theta_8, 0], I, X, Z, X), ...
                kron( D([0, estimated_angles(1), estimated_angles(2), 0], I, X, Z, X), ... 
                   kron( D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X),   ...
                     kron( D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                        kron( D([0, theta_15, theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_4 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               theta_5,theta_6, ...
               theta_7,theta_8, ...
               estimated_angles(1), estimated_angles(2),...
               estimated_angles(3), estimated_angles(4),...
               theta_13, theta_14,...
               theta_15, theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X4Z5 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_4);

    writematrix ([Sample_4,j],'Data_10qubit.csv','WriteMode','append');

    % End of fifth case 
    %---------------------------------------------------------------------
    % Fifth case: X5Z6 

    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- I ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- X ----D(0, theta_11, theta_12, 0) ---
    % ---- Z ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X5Z6 = kron(I, ...
            kron(I, ...
                kron(I, ...
                    kron(I, ...
                        kron(I, ...
                            kron (X, ...
                               kron(Z, ...
                                 kron(I, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X5Z6;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
           D([0, theta_13, theta_14, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, theta_5,theta_6, 0) ---
    % --- D(0, theta_7,theta_8, 0) ---
    % ----D(0, theta_9,theta_10, 0) ---
    % ----D(0, estimated_angles(1), estimated_angles(2), 0) ---
    % ----D(0, estimated_angles(3), estimated_angles(4), 0) ---
    % ----D(0, theta_15, theta_16, 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, theta_5,theta_6, 0], I, X, Z, X), ...
             kron( D([0, theta_7,theta_8, 0], I, X, Z, X), ...
                kron( D([0, theta_9,theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, estimated_angles(1), estimated_angles(2), 0], I, X, Z, X),   ...
                     kron( D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X), ...
                        kron( D([0, theta_15, theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_5 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               theta_5,theta_6, ...
               theta_7,theta_8, ...
               theta_9,theta_10,...
               estimated_angles(1), estimated_angles(2),...
               estimated_angles(3), estimated_angles(4),...
               theta_15, theta_16,...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X5Z6 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_5);
    writematrix ([Sample_5,j],'Data_10qubit.csv','WriteMode','append');


    % End of fifth case 
    %---------------------------------------------------------------------
    % Sixth case: X6Z7 

    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- I ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- X ----D(0, theta_13, theta_14, 0) ---
    % ---- Z ----D(0, theta_15, theta_16, 0) ---
    % ---- I ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X6Z7 = kron(I, ...
            kron(I, ...
                kron(I, ...
                    kron(I, ...
                        kron(I, ...
                            kron (I, ...
                               kron(X, ...
                                 kron(Z, ...
                                    kron (I, ...
                                            I...
                    )))))))));
    
    A = R*X6Z7;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_13, theta_14, 0], I, X, Z, X), ...
           D([0, theta_15, theta_16, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, theta_5,theta_6, 0) ---
    % --- D(0, theta_7,theta_8, 0) ---
    % ----D(0, theta_9,theta_10, 0) ---
    % ----D(0, theta_11,theta_12, 0) ---
    % ----D(0, estimated_angles(1), estimated_angles(2), 0) ---
    % ----D(0, estimated_angles(3), estimated_angles(4), 0) -------------------------
    % ----D(0, theta_17, theta_18, 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, theta_5,theta_6, 0], I, X, Z, X), ...
             kron( D([0, theta_7,theta_8, 0], I, X, Z, X), ...
                kron( D([0, theta_9,theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, theta_11,theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, estimated_angles(1), estimated_angles(2), 0], I, X, Z, X), ...
                        kron( D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X), ... 
                            kron( D([0, theta_17, theta_18, 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_6 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               theta_5,theta_6, ...
               theta_7,theta_8, ...
               theta_9,theta_10,...
               theta_11,theta_12,...
               estimated_angles(1), estimated_angles(2),...
               estimated_angles(3), estimated_angles(4),...
               theta_17,theta_18,...
               theta_19,theta_20];
    fprintf ('Sample R*X6Z7 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_6);

    writematrix ([Sample_6,j],'Data_10qubit.csv','WriteMode','append');

    % End of sixth case 
    %---------------------------------------------------------------------
    % Seventh case: X7Z8 

    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- I ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- X ----D(0, theta_15, theta_16, 0) ---
    % ---- Z ----D(0, theta_17, theta_18, 0) ---
    % ---- I ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X7Z8 = kron(I, ...
            kron(I, ...
                kron(I, ...
                    kron(I, ...
                        kron(I, ...
                            kron (I, ...
                               kron(I, ...
                                 kron(X, ...
                                    kron (Z, ...
                                            I...
                    )))))))));
    
    A = R*X7Z8;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_15, theta_16, 0], I, X, Z, X), ...
           D([0, theta_17, theta_18, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, theta_5,theta_6, 0) ---
    % --- D(0, theta_7,theta_8, 0) ---
    % ----D(0, theta_9,theta_10, 0) ---
    % ----D(0, theta_11,theta_12, 0) ---
    % ----D(0, theta_13,theta_14, 0) ---
    % ----D(0, estimated_angles(1), estimated_angles(2), 0) -------------------------
    % ----D(0, estimated_angles(3), estimated_angles(4), 0) ------------------------
    % ----D(0, theta_19, theta_20, 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, theta_5,theta_6, 0], I, X, Z, X), ...
             kron( D([0, theta_7,theta_8, 0], I, X, Z, X), ...
                kron( D([0, theta_9,theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, theta_11,theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, theta_13,theta_14, 0], I, X, Z, X), ...
                        kron( D([0, estimated_angles(1), estimated_angles(2), 0], I, X, Z, X), ... 
                            kron( D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X),   ...
                                    D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_7 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               theta_5,theta_6, ...
               theta_7,theta_8, ...
               theta_9,theta_10,...
               theta_11,theta_12,...
               theta_13,theta_14,...
               estimated_angles(1), estimated_angles(2),...
               estimated_angles(3), estimated_angles(4),...
               theta_19,theta_20];
    fprintf ('Sample R*X7Z8 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_7);

    writematrix ([Sample_7,j],'Data_10qubit.csv','WriteMode','append');

    % End of Seventh case 
    %---------------------------------------------------------------------
    % Eighth case: X7Z8 

    % ---  I --- D(0, theta_1, theta_2, 0) --- 
    % ---  I --- D(0, theta_3, theta_4, 0) --- 
    % ---- I ----D(0, theta_5, theta_6, 0) ---
    % ---- I ----D(0, theta_7, theta_8, 0) ---
    % ---- I ----D(0, theta_9, theta_10, 0) ---
    % ---- I ----D(0, theta_11, theta_12, 0) ---
    % ---- I ----D(0, theta_13, theta_14, 0) ---
    % ---- I ----D(0, theta_15, theta_16, 0) ---
    % ---- X ----D(0, theta_17, theta_18, 0) ---
    % ---- Z ----D(0, theta_19, theta_20, 0) ---

    
    % Rotations  
    R = kron(D([0, theta_1, theta_2, 0], I, X, Z, X), ...
         kron(D([0, theta_3, theta_4, 0], I, X, Z, X), ...
           kron(D([0, theta_5, theta_6, 0], I, X, Z, X), ...
             kron(D([0, theta_7, theta_8, 0], I, X, Z, X), ...
                kron(D([0, theta_9, theta_10, 0], I, X, Z, X), ... 
                   kron(D([0, theta_11, theta_12, 0], I, X, Z, X), ...
                      kron (D([0, theta_13, theta_14, 0], I, X, Z, X), ...
                         kron (D([0, theta_15, theta_16, 0], I, X, Z, X), ...
                           kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
                               (D([0, theta_19, theta_20, 0], I, X, Z, X) ...
                                                             ))))))))));
    % Stabilizer 
    X8Z9 = kron(I, ...
            kron(I, ...
                kron(I, ...
                    kron(I, ...
                        kron(I, ...
                            kron (I, ...
                               kron(I, ...
                                 kron(I, ...
                                    kron (X, ...
                                            Z...
                    )))))))));
    
    A = R*X8Z9;
    
    % We parametrise the matrix by using first two qbits 
    M0 = kron(D([0, theta_17, theta_18, 0], I, X, Z, X), ...
           D([0, theta_19, theta_20, 0], I, X, Z, X)     );
    
    S0= kron(X,Z);
    B0 = M0*S0;
    
    % Recalculate angles 
    estimated_angles = DxD_Euler_angles (B0);
    

    % Equivalent Matrix 
    % --- D(0, theta_1,theta_2, 0) --- 
    % --- D(0, theta_3,theta_4, 0) --- 
    % --- D(0, theta_5,theta_6, 0) ---
    % --- D(0, theta_7,theta_8, 0) ---
    % ----D(0, theta_9,theta_10, 0) ---
    % ----D(0, theta_11,theta_12, 0) ---
    % ----D(0, theta_13,theta_14, 0) ---
    % ----D(0, theta_15,theta_16, 0) -------------------------
    % ----D(0, estimated_angles(3), estimated_angles(4), 0) ------------------------
    % ----D(0, estimated_angles(3), estimated_angles(4), 0) ------------------------
    
                                                   
    A0 = kron(D([0,theta_1,theta_2, 0], I,X,Z,X), ...
          kron( D([0, theta_3,theta_4, 0, 0], I,X,Z,X), ...
           kron( D([0, theta_5,theta_6, 0], I, X, Z, X), ...
             kron( D([0, theta_7,theta_8, 0], I, X, Z, X), ...
                kron( D([0, theta_9,theta_10, 0], I, X, Z, X), ... 
                   kron( D([0, theta_11,theta_12, 0], I, X, Z, X),   ...
                     kron( D([0, theta_13,theta_14, 0], I, X, Z, X), ...
                        kron( D([0, theta_15,theta_16, 0], I, X, Z, X), ... 
                            kron( D([0, estimated_angles(1), estimated_angles(2), 0], I, X, Z, X),   ...
                                    D([0, estimated_angles(3), estimated_angles(4), 0], I, X, Z, X) ...
                                                             )))))))));                                            
    
    %test 
    if norm (A-A0)  >= 0.001
         fprintf ('Matrix angles estgimation warning\n');
         return
    else

    end
    
    % Therefore, sample is 
    Sample_8 = [ theta_1,theta_2, ...
               theta_3,theta_4, ...
               theta_5,theta_6, ...
               theta_7,theta_8, ...
               theta_9,theta_10,...
               theta_11,theta_12,...
               theta_13,theta_14,...
               theta_15,theta_16,...
               estimated_angles(1), estimated_angles(2),...
               estimated_angles(3), estimated_angles(4)];
    fprintf ('Sample R*X8Z9 =  %.2f, %.2f, %.2f, %.2f, %.2f,%.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f,%.2f\n',...
              Sample_8);

    writematrix ([Sample_8,j],'Data_10qubit.csv','WriteMode','append');
%---------------------------------------------------------------------
% Generate Dataset
    for r = 1:samples

%c_minus*s_1
        writematrix ([[Sample_0(1),Sample_0(2),Sample_0(3),Sample_0(4),Sample_0(5),Sample_0(6),Sample_0(7),Sample_0(8),Sample_0(9),Sample_0(10),Sample_0(11),Sample_0(12),Sample_0(13),Sample_0(14),Sample_0(15),Sample_0(16),Sample_0(17),Sample_0(18),Sample_0(19),Sample_0(20)] + ...
            [Sample_0(1)*random("Normal",0,sqrt(eps)),Sample_0(2)*random("Normal",0,sqrt(eps)),Sample_0(3)*random("Normal",0,sqrt(eps)), ...
            Sample_0(4)*random("Normal",0,sqrt(eps)),Sample_0(5)*random("Normal",0,sqrt(eps)),Sample_0(6)*random("Normal",0,sqrt(eps)), ...
            Sample_0(7)*random("Normal",0,sqrt(eps)),Sample_0(8)*random("Normal",0,sqrt(eps)),Sample_0(9)*random("Normal",0,sqrt(eps)),Sample_0(10)*random("Normal",0,sqrt(eps)), ...
            Sample_0(11)*random("Normal",0,sqrt(eps)),Sample_0(12)*random("Normal",0,sqrt(eps)),Sample_0(13)*random("Normal",0,sqrt(eps)),Sample_0(14)*random("Normal",0,sqrt(eps)),...
            Sample_0(15)*random("Normal",0,sqrt(eps)),Sample_0(16)*random("Normal",0,sqrt(eps)),Sample_0(17)*random("Normal",0,sqrt(eps)),Sample_0(18)*random("Normal",0,sqrt(eps)),...
            Sample_0(19)*random("Normal",0,sqrt(eps)),Sample_0(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

        writematrix ([[Sample_1(1),Sample_1(2),Sample_1(3),Sample_1(4),Sample_1(5),Sample_1(6),Sample_1(7),Sample_1(8),Sample_1(9),Sample_1(10),Sample_1(11),Sample_1(12),Sample_1(13),Sample_1(14),Sample_1(15),Sample_1(16),Sample_1(17),Sample_1(18),Sample_1(19),Sample_1(20)] + ...
            [Sample_1(1)*random("Normal",0,sqrt(eps)),Sample_1(2)*random("Normal",0,sqrt(eps)),Sample_1(3)*random("Normal",0,sqrt(eps)), ...
            Sample_1(4)*random("Normal",0,sqrt(eps)),Sample_1(5)*random("Normal",0,sqrt(eps)),Sample_1(6)*random("Normal",0,sqrt(eps)), ...
            Sample_1(7)*random("Normal",0,sqrt(eps)),Sample_1(8)*random("Normal",0,sqrt(eps)),Sample_1(9)*random("Normal",0,sqrt(eps)),Sample_1(10)*random("Normal",0,sqrt(eps)), ...
            Sample_1(11)*random("Normal",0,sqrt(eps)),Sample_1(12)*random("Normal",0,sqrt(eps)),Sample_1(13)*random("Normal",0,sqrt(eps)),Sample_1(14)*random("Normal",0,sqrt(eps)),...
            Sample_1(15)*random("Normal",0,sqrt(eps)),Sample_1(16)*random("Normal",0,sqrt(eps)),Sample_1(17)*random("Normal",0,sqrt(eps)),Sample_1(18)*random("Normal",0,sqrt(eps)),...
            Sample_1(19)*random("Normal",0,sqrt(eps)),Sample_1(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

        writematrix ([[Sample_2(1),Sample_2(2),Sample_2(3),Sample_2(4),Sample_2(5),Sample_2(6),Sample_2(7),Sample_2(8),Sample_2(9),Sample_2(10),Sample_2(11),Sample_2(12),Sample_2(13),Sample_2(14),Sample_2(15),Sample_2(16),Sample_2(17),Sample_2(18),Sample_2(19),Sample_2(20)] + ...
            [Sample_2(1)*random("Normal",0,sqrt(eps)),Sample_2(2)*random("Normal",0,sqrt(eps)),Sample_2(3)*random("Normal",0,sqrt(eps)), ...
            Sample_2(4)*random("Normal",0,sqrt(eps)),Sample_2(5)*random("Normal",0,sqrt(eps)),Sample_2(6)*random("Normal",0,sqrt(eps)), ...
            Sample_2(7)*random("Normal",0,sqrt(eps)),Sample_2(8)*random("Normal",0,sqrt(eps)),Sample_2(9)*random("Normal",0,sqrt(eps)),Sample_2(10)*random("Normal",0,sqrt(eps)), ...
            Sample_2(11)*random("Normal",0,sqrt(eps)),Sample_2(12)*random("Normal",0,sqrt(eps)),Sample_2(13)*random("Normal",0,sqrt(eps)),Sample_2(14)*random("Normal",0,sqrt(eps)),...
            Sample_2(15)*random("Normal",0,sqrt(eps)),Sample_2(16)*random("Normal",0,sqrt(eps)),Sample_2(17)*random("Normal",0,sqrt(eps)),Sample_2(18)*random("Normal",0,sqrt(eps)),...
            Sample_2(19)*random("Normal",0,sqrt(eps)),Sample_2(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

        writematrix ([[Sample_3(1),Sample_3(2),Sample_3(3),Sample_3(4),Sample_3(5),Sample_3(6),Sample_3(7),Sample_3(8),Sample_3(9),Sample_3(10),Sample_3(11),Sample_3(12),Sample_3(13),Sample_3(14),Sample_3(15),Sample_3(16),Sample_3(17),Sample_3(18),Sample_3(19),Sample_3(20)] + ...
            [Sample_3(1)*random("Normal",0,sqrt(eps)),Sample_3(2)*random("Normal",0,sqrt(eps)),Sample_3(3)*random("Normal",0,sqrt(eps)), ...
            Sample_3(4)*random("Normal",0,sqrt(eps)),Sample_3(5)*random("Normal",0,sqrt(eps)),Sample_3(6)*random("Normal",0,sqrt(eps)), ...
            Sample_3(7)*random("Normal",0,sqrt(eps)),Sample_3(8)*random("Normal",0,sqrt(eps)),Sample_3(9)*random("Normal",0,sqrt(eps)),Sample_3(10)*random("Normal",0,sqrt(eps)), ...
            Sample_3(11)*random("Normal",0,sqrt(eps)),Sample_3(12)*random("Normal",0,sqrt(eps)),Sample_3(13)*random("Normal",0,sqrt(eps)),Sample_3(14)*random("Normal",0,sqrt(eps)),...
            Sample_3(15)*random("Normal",0,sqrt(eps)),Sample_3(16)*random("Normal",0,sqrt(eps)),Sample_3(17)*random("Normal",0,sqrt(eps)),Sample_3(18)*random("Normal",0,sqrt(eps)),...
            Sample_3(19)*random("Normal",0,sqrt(eps)),Sample_3(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

        writematrix ([[Sample_4(1),Sample_4(2),Sample_4(3),Sample_4(4),Sample_4(5),Sample_4(6),Sample_4(7),Sample_4(8),Sample_4(9),Sample_4(10),Sample_4(11),Sample_4(12),Sample_4(13),Sample_4(14),Sample_4(15),Sample_4(16),Sample_4(17),Sample_4(18),Sample_4(19),Sample_4(20)] + ...
            [Sample_4(1)*random("Normal",0,sqrt(eps)),Sample_4(2)*random("Normal",0,sqrt(eps)),Sample_4(3)*random("Normal",0,sqrt(eps)), ...
            Sample_4(4)*random("Normal",0,sqrt(eps)),Sample_4(5)*random("Normal",0,sqrt(eps)),Sample_4(6)*random("Normal",0,sqrt(eps)), ...
            Sample_4(7)*random("Normal",0,sqrt(eps)),Sample_4(8)*random("Normal",0,sqrt(eps)),Sample_4(9)*random("Normal",0,sqrt(eps)),Sample_4(10)*random("Normal",0,sqrt(eps)), ...
            Sample_4(11)*random("Normal",0,sqrt(eps)),Sample_4(12)*random("Normal",0,sqrt(eps)),Sample_4(13)*random("Normal",0,sqrt(eps)),Sample_4(14)*random("Normal",0,sqrt(eps)),...
            Sample_4(15)*random("Normal",0,sqrt(eps)),Sample_4(16)*random("Normal",0,sqrt(eps)),Sample_4(17)*random("Normal",0,sqrt(eps)),Sample_4(18)*random("Normal",0,sqrt(eps)),...
            Sample_4(19)*random("Normal",0,sqrt(eps)),Sample_4(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

        writematrix ([[Sample_5(1),Sample_5(2),Sample_5(3),Sample_5(4),Sample_5(5),Sample_5(6),Sample_5(7),Sample_5(8),Sample_5(9),Sample_5(10),Sample_5(11),Sample_5(12),Sample_5(13),Sample_5(14),Sample_5(15),Sample_5(16),Sample_5(17),Sample_5(18),Sample_5(19),Sample_5(20)] + ...
            [Sample_5(1)*random("Normal",0,sqrt(eps)),Sample_5(2)*random("Normal",0,sqrt(eps)),Sample_5(3)*random("Normal",0,sqrt(eps)), ...
            Sample_5(4)*random("Normal",0,sqrt(eps)),Sample_5(5)*random("Normal",0,sqrt(eps)),Sample_5(6)*random("Normal",0,sqrt(eps)), ...
            Sample_5(7)*random("Normal",0,sqrt(eps)),Sample_5(8)*random("Normal",0,sqrt(eps)),Sample_5(9)*random("Normal",0,sqrt(eps)),Sample_5(10)*random("Normal",0,sqrt(eps)), ...
            Sample_5(11)*random("Normal",0,sqrt(eps)),Sample_5(12)*random("Normal",0,sqrt(eps)),Sample_5(13)*random("Normal",0,sqrt(eps)),Sample_5(14)*random("Normal",0,sqrt(eps)),...
            Sample_5(15)*random("Normal",0,sqrt(eps)),Sample_5(16)*random("Normal",0,sqrt(eps)),Sample_5(17)*random("Normal",0,sqrt(eps)),Sample_5(18)*random("Normal",0,sqrt(eps)),...
            Sample_5(19)*random("Normal",0,sqrt(eps)),Sample_5(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

          writematrix ([[Sample_6(1),Sample_6(2),Sample_6(3),Sample_6(4),Sample_6(5),Sample_6(6),Sample_6(7),Sample_6(8),Sample_6(9),Sample_6(10),Sample_6(11),Sample_6(12),Sample_6(13),Sample_6(14),Sample_6(15),Sample_6(16),Sample_6(17),Sample_6(18),Sample_6(19),Sample_6(20)] + ...
            [Sample_6(1)*random("Normal",0,sqrt(eps)),Sample_6(2)*random("Normal",0,sqrt(eps)),Sample_6(3)*random("Normal",0,sqrt(eps)), ...
            Sample_6(4)*random("Normal",0,sqrt(eps)),Sample_6(5)*random("Normal",0,sqrt(eps)),Sample_6(6)*random("Normal",0,sqrt(eps)), ...
            Sample_6(7)*random("Normal",0,sqrt(eps)),Sample_6(8)*random("Normal",0,sqrt(eps)),Sample_6(9)*random("Normal",0,sqrt(eps)),Sample_6(10)*random("Normal",0,sqrt(eps)), ...
            Sample_6(11)*random("Normal",0,sqrt(eps)),Sample_6(12)*random("Normal",0,sqrt(eps)),Sample_6(13)*random("Normal",0,sqrt(eps)),Sample_6(14)*random("Normal",0,sqrt(eps)),...
            Sample_6(15)*random("Normal",0,sqrt(eps)),Sample_6(16)*random("Normal",0,sqrt(eps)),Sample_6(17)*random("Normal",0,sqrt(eps)),Sample_6(18)*random("Normal",0,sqrt(eps)),...
            Sample_6(19)*random("Normal",0,sqrt(eps)),Sample_6(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

           writematrix ([[Sample_7(1),Sample_7(2),Sample_7(3),Sample_7(4),Sample_7(5),Sample_7(6),Sample_7(7),Sample_7(8),Sample_7(9),Sample_7(10),Sample_7(11),Sample_7(12),Sample_7(13),Sample_7(14),Sample_7(15),Sample_7(16),Sample_7(17),Sample_7(18),Sample_7(19),Sample_7(20)] + ...
            [Sample_7(1)*random("Normal",0,sqrt(eps)),Sample_7(2)*random("Normal",0,sqrt(eps)),Sample_7(3)*random("Normal",0,sqrt(eps)), ...
            Sample_7(4)*random("Normal",0,sqrt(eps)),Sample_7(5)*random("Normal",0,sqrt(eps)),Sample_7(6)*random("Normal",0,sqrt(eps)), ...
            Sample_7(7)*random("Normal",0,sqrt(eps)),Sample_7(8)*random("Normal",0,sqrt(eps)),Sample_7(9)*random("Normal",0,sqrt(eps)),Sample_7(10)*random("Normal",0,sqrt(eps)), ...
            Sample_7(11)*random("Normal",0,sqrt(eps)),Sample_7(12)*random("Normal",0,sqrt(eps)),Sample_7(13)*random("Normal",0,sqrt(eps)),Sample_7(14)*random("Normal",0,sqrt(eps)),...
            Sample_7(15)*random("Normal",0,sqrt(eps)),Sample_7(16)*random("Normal",0,sqrt(eps)),Sample_7(17)*random("Normal",0,sqrt(eps)),Sample_7(18)*random("Normal",0,sqrt(eps)),...
            Sample_7(19)*random("Normal",0,sqrt(eps)),Sample_7(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

           writematrix ([[Sample_8(1),Sample_8(2),Sample_8(3),Sample_8(4),Sample_8(5),Sample_8(6),Sample_8(7),Sample_8(8),Sample_8(9),Sample_8(10),Sample_8(11),Sample_8(12),Sample_8(13),Sample_8(14),Sample_8(15),Sample_8(16),Sample_8(17),Sample_8(18),Sample_8(19),Sample_8(20)] + ...
            [Sample_8(1)*random("Normal",0,sqrt(eps)),Sample_8(2)*random("Normal",0,sqrt(eps)),Sample_8(3)*random("Normal",0,sqrt(eps)), ...
            Sample_8(4)*random("Normal",0,sqrt(eps)),Sample_8(5)*random("Normal",0,sqrt(eps)),Sample_8(6)*random("Normal",0,sqrt(eps)), ...
            Sample_8(7)*random("Normal",0,sqrt(eps)),Sample_8(8)*random("Normal",0,sqrt(eps)),Sample_8(9)*random("Normal",0,sqrt(eps)),Sample_8(10)*random("Normal",0,sqrt(eps)), ...
            Sample_8(11)*random("Normal",0,sqrt(eps)),Sample_8(12)*random("Normal",0,sqrt(eps)),Sample_8(13)*random("Normal",0,sqrt(eps)),Sample_8(14)*random("Normal",0,sqrt(eps)),...
            Sample_8(15)*random("Normal",0,sqrt(eps)),Sample_8(16)*random("Normal",0,sqrt(eps)),Sample_8(17)*random("Normal",0,sqrt(eps)),Sample_8(18)*random("Normal",0,sqrt(eps)),...
            Sample_8(19)*random("Normal",0,sqrt(eps)),Sample_8(20)*random("Normal",0,sqrt(eps))] ...
            ,j],'Data_10qubit.csv','WriteMode','append');

    end
 end  
end

end



%------------------------------------------------------------------------
% DxD_Euler_angles : Caluclates the Euler angles for a SU(4) = DxD matitx
%------------------------------------------------------------------------
function angles = DxD_Euler_angles (M)

%M is SU(4)
I= [ 1 0 0 0 
     0 1 0 0 
     0 0 1 0 
     0 0 0 1 ];
 if norm(M*M'-I) >= 0.001    % not U4
     angles=[0 0 0 0];
     return
 elseif det(M)-1 >= 0.001  % not SU(4)
     angles = [0 0 0 0];
     return
 end
         

% Using M explicit expressions 
% M(1,2)= -cos(theta_1/2)*sin(theta_3/2)*exp(-(theta_2*1i)/2)*exp((theta_4*1i)/2)*1i;
% M(1,1) = cos(theta_1/2)*cos(theta_3/2)*exp(-(theta_2*1i)/2)*exp(-(theta_4*1i)/2); 
theta_3 =   2*atan( abs(M(1,2)/M(1,1)) );

% M(1,4) = -sin(theta_1/2)*sin(theta_3/2)*exp((theta_2*1i)/2)*exp((theta_4*1i)/2);
% M(2,1) = -cos(theta_1/2)*sin(theta_3/2)*exp(-(theta_2*1i)/2)*exp(-(theta_4*1i)/2)*1i; 
theta_1 =   2*atan( abs(M(1,4)/M(2,1)) );

% M(2,2)= cos(theta_1/2)*cos(theta_3/2)*exp(-(theta_2*1i)/2)*exp((theta_4*1i)/2);
% M(1,1) = cos(theta_1/2)*cos(theta_3/2)*exp(-(theta_2*1i)/2)*exp(-(theta_4*1i)/2);
theta_4 =  angle(M(2,2)) - angle (M (1,1));

% M(1,4) = -sin(theta_1/2)*sin(theta_3/2)*exp((theta_2*1i)/2)*exp((theta_4*1i)/2);
% M(2,3) = -sin(theta_1/2)*sin(theta_3/2)*exp((theta_2*1i)/2)*exp(-(theta_4*1i)/2);
theta_2 = angle(M(1,4)) + angle(M(2,3));

%Angle correction to [-pi/2, pi/2]
if theta_2 >= 3*pi/4
    theta_2 = 2*pi - theta_2;
end
if theta_2 <= -3*pi/4
    theta_2 = 2*pi + theta_2;
end


% Angle correction to [-pi/2,pi/2]
% M(1,2)= -cos(theta_1/2)*sin(theta_3/2)*exp(-(theta_2*1i)/2)*exp((theta_4*1i)/2)*1i;
if  M(1,2)/(exp(-(theta_2*1i)/2)*exp((theta_4*1i)/2)*1i) >= 0.0
    if theta_3 >= 0.0
       theta_3 = -theta_3;
    end
end

% Angle correction to [-pi/2,pi/2]
% M(1,3) = -cos(theta_3/2)*sin(theta_1/2)*exp((theta_2*1i)/2)*exp(-(theta_4*1i)/2)*1i;
if M(1,3)/( exp((theta_2*1i)/2)*exp(-(theta_4*1i)/2)*1i ) >= 0.0
    if theta_1 >= 0.0
       theta_1 = -theta_1;
    end
end
    
% M(1,1) = cos(theta_1/2)*cos(theta_3/2)*exp(-(theta_2*1i)/2)*exp(-(theta_4*1i)/2); 
if abs(M(1,1) - cos(theta_1/2)*cos(theta_3/2)*exp(-(theta_2*1i)/2)*exp(-(theta_4*1i)/2)) >= 0.001
    theta_2 = -theta_2;
end

%Return results
angles = [theta_1 theta_2 theta_3 theta_4 ];


end



%-------------------------------------------------------------------------
%  D : returns the product of the exponentials of the three square matrices
%      A1, A2, A3 and A4  as  D = exp(-ia1A1/2)*exp(-ia2A2/2)*exp(-ia3A3/2)
%      *exp(-ia4A4/2)
%-------------------------------------------------------------------------
function M = D (angles, A1, A2, A3, A4)
    % Use of matrix exponentials 
    M =  expm(-1i*angles(1)*A1/2)...
        *expm(-1i*angles(2)*A2/2)...
        *expm(-1i*angles(3)*A3/2)...
        *expm(-1i*angles(4)*A4/2);
end
